POST http://localhost:4000/api/admin HTTP/1.1
content-type: application/json

{
    "avatar": "https://firebasestorage.googleapis.com/v0/b/sonik-shop.appspot.com/o/AvatarMaker.png?alt=media&token=c78aad0f-b5f0-4075-b74c-ada86d084fc0",
    "name": "Kode Sonik",
    "phoneNumber": "+22892942601",
    "email": "k0d3.s0n1k@gmail.com"
}

###

POST http://localhost:4000/api/employee HTTP/1.1
content-type: application/json

{
    "avatar": "https://firebasestorage.googleapis.com/v0/b/sonik-shop.appspot.com/o/AvatarMaker.png?alt=media&token=c78aad0f-b5f0-4075-b74c-ada86d084fc0",
    "name": "Etienne KAPOUE",
    "phoneNumber": "+22890000003",
    "shopId": "CZX5RuHRMaAe2eE5qo8f"
}